# multi gpu
# distributed_type: MULTI_GPU
# gpu_ids: 0,1,2,3,4,5,6,7
# num_processes: 8

# single gpu
distributed_type: NO
num_processes: 1

compute_environment: LOCAL_MACHINE
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
