name: "themestation-optimization"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 42

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [1.4, 1.8]
  fovy_range: [70, 80]
  elevation_range: [-5, 30]
  input_image_elevation_offset: 0
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.5
  eval_fovy_deg: 70.
  n_val_views: 8
  n_test_views: 180

system_type: "themestation-system"
system:
  stage: dsd
  use_reference_model_dreambooth: true
  use_base_model_dreambooth: true
  use_prompt_norm: true
  start_mesh_deformation_step: 5000 # -1 means not using deformation
  use_contextual_loss: true
  use_rgb_contextual_loss: true
  use_tv_loss: true
  visualize_samples: false
  geometry_convert_from: ???
  prev_cfg_dir: ??? # parsed.yaml path
  geometry_type: implicit-sdf # modify
  geometry_convert_inherit_texture: true
  geometry: # modify
    radius: 1.0
    feature_dim: 13 # modify
    normal_type: finite_difference # modify
    finite_difference_normal_eps: progressive # modify
    isosurface_deformable_grid: true
    isosurface_resolution: 192 # consistent with last stage
    isosurface_remove_outliers: false
    pos_encoding_config: # modify
      otype: ProgressiveBandHashGrid
      n_levels: 10
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
      start_level: 4
      start_step: 0
      update_steps: 1000
      global_step_offset: 5000 # = Wonder3D training steps + previous optimization steps
    mlp_network_config:
      otype: VanillaMLPWon3D
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
  
  material_convert_from: ??? # .ckpt path
  material_type: "neural-radiance-material"
  material:
    input_feature_dims: 16 #
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLPWon3D
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    dreambooth_ckpt_path: ""
    use_cache: false
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.

  prompt_norm_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    dreambooth_ckpt_path: ""
    use_cache: false
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.  

  ref_prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    dreambooth_ckpt_path: ""
    use_cache: false
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.

  ref_prompt_norm_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    dreambooth_ckpt_path: ""
    use_cache: false
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    dreambooth_ckpt_path: ""
    half_precision_weights: false
    use_camera_embedding: false
    guidance_scale: 7.5
    min_step_percent: [5000, 0.5, 0.6, 5001] # default: 0.02
    max_step_percent: [5000, 0.75, 0.85, 5001] #[5000, 0.8, 0.5, 5001] # default: [5000, 0.98, 0.5, 5001] annealed to 0.5 after 5000 steps


  ref_guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    dreambooth_ckpt_path: ""
    half_precision_weights: false
    use_camera_embedding: false
    guidance_scale: 7.5
    min_step_percent: [5000, 0.1, 0.02, 5001] # default: 0.02
    max_step_percent: [5000, 0.25, 0.15, 5001] # 0.5, 0.4 #[5000, 0.8, 0.5, 5001] # default: [5000, 0.98, 0.5, 5001] annealed to 0.5 after 5000 steps

  ref_norm_guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    dreambooth_ckpt_path: ""
    half_precision_weights: false
    use_camera_embedding: false
    guidance_scale: 7.5
    min_step_percent: [5000, 0.1, 0.02, 5001] # default: 0.02
    max_step_percent: [5000, 0.25, 0.15, 5001] # 0.5, 0.4 #[5000, 0.8, 0.5, 5001] # default: [5000, 0.98, 0.5, 5001] annealed to 0.5 after 5000 steps


  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_vsd: 0.2
    lambda_lora: 0.2
    lambda_ref_vsd: 1.
    lambda_ref_lora: 1.
    lambda_orient: 0.
    lambda_sparsity: 10.
    lambda_opaque: [2500, 0.0, 1000, 2501]
    lambda_normal_consistency: 400.
    lambda_laplacian_smoothness: 0.
    lambda_contextual_rgb: 100.
    lambda_tv: 8e-4
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params: # init lr
      geometry.encoding:
        lr: 0.0001
      geometry.network:
        lr: 0.00002
      geometry.sdf: # unused
        lr: 0.
      geometry.deformation: # unused
        lr: 0.
      material.network: #
        lr: 0.00002

      guidance:
        lr: 0.0001
      ref_guidance:
        lr: 0.0001
      background:
        lr: 0.0001
    update_lr_at_certain_step: True
    milestone: 5000
    new_lr: # lr after milestone
      geometry.encoding:
        lr: 0.00005
      geometry.network:
        lr: 0.00001
      geometry.sdf: # unused
        lr: 0.
      geometry.deformation: # unused
        lr: 0.
      material.network:
        lr: 0.0005

      guidance:
        lr: 0.0001
      ref_guidance:
        lr: 0.0001
      background:
        lr: 0.0001
      
        
trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 8
  val_check_interval: 100
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
